---
version: "3.4"
services:
  prd-ntp-server-app:
    image: docker-registry.theautomation.nl/coen/prd-ntp-server-app
    container_name: prd-ntp-server-app
    restart: always
    env_file: prd-ntp-server-app.env
    ports:
      - 123:123/udp
    read_only: true
    networks:
      - ntp-server
    tmpfs:
      - /etc/chrony:rw,mode=1750
      - /run/chrony:rw,mode=1750
      - /var/lib/chrony:rw,mode=1750

networks:
  ntp-server:
    name: ntp-server
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
